### ISSUE TITLE
Harmless is stuck

### ISSUE THREAD

**Issue by pickfire** [timebug/harmless#1]
The midgame:
![2015-10-10-172519_530x586_scrot](https://cloud.githubusercontent.com/assets/4687791/10410489/4ac09ee4-6f75-11e5-9148-e5c8a962938b.png)
Ending:
![2015-10-10-173403_530x586_scrot](https://cloud.githubusercontent.com/assets/4687791/10410490/53ec978e-6f75-11e5-8be2-d974202593a5.png)
But it seems like it is stuck there forever. The AI doesn't move.

**Comment by timebug** [comment]
Thank you for your feedback, I will try to fix it some day.
