### ISSUE TITLE
Will you support on python3?

### ISSUE THREAD

**Issue by elcolie** [timebug/harmless#2]
Will you support on python3?

**Comment by timebug** [comment]
Sorry, I haven't planned yet.

**Comment by pickfire** [comment]
@timebug I can help to support python 3 or add 2 player support. Quite enjoy the game. (my computer got so hot)

![2017-08-31-132530_530x586_scrot](https://user-images.githubusercontent.com/4687791/29907781-1d954ee6-8e50-11e7-8d29-dc867a747863.png)

**Comment by timebug** [comment]
@pickfire 

> I can help to support python 3 or add 2 player support.

Welcome pull request :-)

But 2 player is supported already, you can improve it. See https://github.com/timebug/harmless/blob/master/pycchess/chessnet.py

**Comment by pickfire** [comment]
@timebug Oh, there is no documentation about it. Looks kinda hard to modify stuff around the code. I kinda feel like creating my own fork that have CLI (later on then GUI).
